name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-psdr:
    name: Install minicondaconda, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
#        python-version: ["3.7", "2.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: psdr
          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: install dependencies
        shell: bash -el {0}
        run: conda install -y -c conda-forge xtensor xtensor-io spdlog cgal mpfr
      - name: pip install
        shell: bash -el {0}
        run: pip install psdr/.
      - name: run tests
        shell: bash -el {0}
        run: python -m unittest psdr/test.py
#  install-conda-dependencies:
#    name: Install dependencies

